export const USERDATA_UPDATE = 'USERDATA_UPDATE';
export const USERDATA_UPLOAD_REQUEST = 'USERDATA_UPLOAD_REQUEST';
export const USERDATA_UPLOAD_SUCCESS = 'USERDATA_UPLOAD_SUCCESS';
export const USERDATA_UPLOAD_FAILURE = 'USERDATA_UPLOAD_FAILURE';